# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

outerProdRow <- function(X) {
    .Call(`_ECCCM_outerProdRow`, X)
}

covRows <- function(cov_mats, m, k) {
    .Call(`_ECCCM_covRows`, cov_mats, m, k)
}

findCovVar <- function(list_cov_mat, cov_mat) {
    .Call(`_ECCCM_findCovVar`, list_cov_mat, cov_mat)
}

findCovBayes <- function(list_cov_mat, cov_mat, delta_gamma) {
    .Call(`_ECCCM_findCovBayes`, list_cov_mat, cov_mat, delta_gamma)
}

findCovByInd <- function(x, ind) {
    .Call(`_ECCCM_findCovByInd`, x, ind)
}

findCovTwoInd <- function(cov_scaled_list, ind_a, ind_b) {
    .Call(`_ECCCM_findCovTwoInd`, cov_scaled_list, ind_a, ind_b)
}

varFirstTerm <- function(beta, omega, cov_list_scaled, ind) {
    .Call(`_ECCCM_varFirstTerm`, beta, omega, cov_list_scaled, ind)
}

quadForm <- function(x, S) {
    .Call(`_ECCCM_quadForm`, x, S)
}

addVarGauss <- function(cov_mat, omega, beta, n_r, n_o) {
    .Call(`_ECCCM_addVarGauss`, cov_mat, omega, beta, n_r, n_o)
}

